name:                address-book
version:             0.1.0.0
github:              "tomphp/address-book"
license:             BSD3
author:              "Tom Oram"
maintainer:          "tom@codept.com"
copyright:           "2017, Tom Oram"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tomphp/address-book#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- mtl
- text
- yaml

library:
  source-dirs: src

executables:
  address-book-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - address-book

tests:
  address-book-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - address-book
